# Generated by Django 5.1.3 on 2024-11-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='booking_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='num_guests',
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
